### ISSUE TITLE
pynsee.sirene.get_all_columns bug

### ISSUE THREAD

**Issue by linogaliana** [InseeFrLab/Py-Insee-Data#36]
Problem detected by @cthiounn

```python
pynsee.sirene.get_all_columns()
```

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/coder/.conda/envs/pythonENSAE/lib/python3.9/site-packages/pynsee/sirene/get_all_columns.py", line 35, in get_all_columns
    df = df.iloc[:,[0,2]]
  File "/home/coder/.conda/envs/pythonENSAE/lib/python3.9/site-packages/pandas/core/indexing.py", line 925, in __getitem__
    return self._getitem_tuple(key)
  File "/home/coder/.conda/envs/pythonENSAE/lib/python3.9/site-packages/pandas/core/indexing.py", line 1506, in _getitem_tuple
    self._has_valid_tuple(tup)
  File "/home/coder/.conda/envs/pythonENSAE/lib/python3.9/site-packages/pandas/core/indexing.py", line 754, in _has_valid_tuple
    self._validate_key(k, i)
  File "/home/coder/.conda/envs/pythonENSAE/lib/python3.9/site-packages/pandas/core/indexing.py", line 1424, in _validate_key
    raise IndexError("positional indexers are out-of-bounds")
```

**Comment by linogaliana** [comment]
La ligne responsable est là :

https://github.com/InseeFrLab/Py-Insee-Data/blob/9faaeb41342290ed5698890ba7ef3948b476f624/pynsee/sirene/get_all_columns.py#L35

En effet, au niveau de cette étape

```python
df
```

```python
                                index               0
0                               siren           XXXXX
1                                 nic           XXXXX
2                               siret            XXXXX
3                           dateDebut      XXXXX
4           dateCreationEtablissement      XXXXX
..                                ...             ...
85     codePaysEtranger2Etablissement            None
86  libellePaysEtranger2Etablissement            None
87             enseigne2Etablissement            None
88             enseigne3Etablissement            None
89   denominationUsuelleEtablissement            None

[90 rows x 2 columns]
```

et donc naturellement `df.iloc[:,[0,2]]` est en échec

**Comment by linogaliana** [comment]
Fix  avec 4474e37 

- [] Testé sur SSPCloud Visual Studio
- [] Testé sur SSPCloud Jupyter
- [] Ajout d'un test
